apiVersion: v1
kind: Service
metadata:
  name: captain-hook-service
  labels:
    name: captain-hook-service
    tier: backend
    maintainer: python
spec:
  ports:
    # The port that this service should serve on.
    - port: 80
      targetPort: 8005
  type: NodePort
# Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: captain-hook
  type: NodePort
